---
- name: Ensure prometheus group exists
  group:
    name: "{{ prometheus_group }}"
    system: yes

- name: Ensure prometheus user exists
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    shell: /bin/false
    create_home: no
    system: yes

- name: Download Prometheus
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: /tmp/prometheus-{{ prometheus_version }}.tar.gz
    mode: '0644'

- name: Extract Prometheus tarball
  unarchive:
    src: /tmp/prometheus-{{ prometheus_version }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool
  notify: restart prometheus

- name: Ensure config and data directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Deploy prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  notify: restart prometheus

- name: Create systemd unit for prometheus
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring
      After=network.target

      [Service]
      User={{ prometheus_user }}
      Group={{ prometheus_group }}
      ExecStart={{ prometheus_bin_dir }}/prometheus --config.file={{ prometheus_config_dir }}/prometheus.yml --storage.tsdb.path={{ prometheus_data_dir }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus

- name: Reload and enable prometheus service
  systemd:
    name: prometheus
    enabled: yes
    daemon_reload: yes
    state: started
